### PR TITLE
feat(system.js): add `sleep` util

### PR DESCRIPTION
**Pull request by jsjoeio**
This adds a function called `sleep` to sleep your display.

## Demo

Related: 
- https://github.com/johnlindquist/kit/discussions/49

### CODE REVIEW

**Comment by jsjoeio** [comment]
Guessing CI failed because it's looking for my branch under your repo?

image

**Comment by johnlindquist** [comment]
@jsjoeio Yah, thanks! It is checking out a branch, yes. I'll fix that up and get this through 👍

**Comment by johnlindquist** [comment]
Thanks @jsjoeio !!!

**Comment by johnlindquist** [comment]
Fyi, this won't appear in the app until I release another app build

**Pull request merged**
